export const moodMap: Record<string, string[]> = {
  sad: ['sad', 'melancholic', 'heartbreak'],
  depressed: ['sad', 'melancholic', 'dark'],
  lonely: ['sad', 'melancholic', 'dark'],
  heartbroken: ['heartbreak', 'sad', 'melancholic'],
  crying: ['sad', 'heartbreak', 'melancholic'],
  empty: ['melancholic', 'sad', 'dark'],
  lost: ['melancholic', 'sad', 'atmospheric'],
  broken: ['heartbreak', 'sad', 'dark'],
  hurt: ['heartbreak', 'sad', 'melancholic'],
  missing: ['melancholic', 'nostalgic', 'sad'],
  hopeless: ['sad', 'dark', 'melancholic'],
  numb: ['melancholic', 'dark', 'ambient'],
  grief: ['sad', 'melancholic', 'dark'],
  hollow: ['melancholic', 'dark', 'sad'],
  drained: ['melancholic', 'chill', 'sad'],
  defeated: ['sad', 'melancholic', 'dark'],
  disappointed: ['sad', 'melancholic', 'dark'],
  regretful: ['melancholic', 'sad', 'nostalgic'],
  bitter: ['angry', 'dark', 'melancholic'],
  betrayed: ['sad', 'angry', 'dark'],
  happy: ['happy', 'peaceful', 'atmospheric'],
  excited: ['happy', 'atmospheric', 'peaceful'],
  joyful: ['happy', 'peaceful', 'ambient'],
  good: ['happy', 'peaceful', 'chill'],
  great: ['happy', 'peaceful', 'atmospheric'],
  blessed: ['happy', 'peaceful', 'ambient'],
  grateful: ['happy', 'peaceful', 'ambient'],
  euphoric: ['happy', 'atmospheric', 'peaceful'],
  proud: ['happy', 'peaceful', 'atmospheric'],
  confident: ['happy', 'atmospheric', 'peaceful'],
  hopeful: ['happy', 'peaceful', 'atmospheric'],
  optimistic: ['happy', 'peaceful', 'ambient'],
  winning: ['happy', 'atmospheric', 'peaceful'],
  chill: ['chill', 'ambient', 'peaceful'],
  relaxed: ['chill', 'peaceful', 'ambient'],
  calm: ['peaceful', 'ambient', 'chill'],
  peaceful: ['peaceful', 'ambient', 'chill'],
  cozy: ['chill', 'peaceful', 'ambient'],
  lazy: ['chill', 'ambient', 'peaceful'],
  sleepy: ['ambient', 'peaceful', 'chill'],
  tired: ['chill', 'ambient', 'melancholic'],
  comfortable: ['chill', 'peaceful', 'ambient'],
  content: ['peaceful', 'chill', 'happy'],
  gentle: ['peaceful', 'ambient', 'chill'],
  meh: ['chill', 'melancholic', 'ambient'],
  bored: ['chill', 'ambient', 'atmospheric'],
  hype: ['happy', 'atmospheric', 'dark'],
  motivated: ['happy', 'atmospheric', 'peaceful'],
  party: ['happy', 'atmospheric', 'ambient'],
  unstoppable: ['happy', 'atmospheric', 'dark'],
  romantic: ['romantic', 'peaceful', 'ambient'],
  love: ['romantic', 'peaceful', 'happy'],
  crush: ['romantic', 'dreamy', 'peaceful'],
  infatuated: ['romantic', 'dreamy', 'atmospheric'],
  longing: ['romantic', 'melancholic', 'sad'],
  yearning: ['romantic', 'melancholic', 'sad'],
  tender: ['romantic', 'peaceful', 'chill'],
  nostalgic: ['nostalgic', 'melancholic', 'atmospheric'],
  nostalgia: ['nostalgic', 'melancholic', 'sad'],
  memories: ['nostalgic', 'melancholic', 'sad'],
  bittersweet: ['melancholic', 'nostalgic', 'sad'],
  night: ['dark', 'atmospheric', 'ambient'],
  midnight: ['dark', 'atmospheric', 'melancholic'],
  '2am': ['dark', 'melancholic', 'atmospheric'],
  '3am': ['dark', 'melancholic', 'atmospheric'],
  late: ['dark', 'chill', 'atmospheric'],
  dark: ['dark', 'melancholic', 'atmospheric'],
  dusk: ['melancholic', 'atmospheric', 'ambient'],
  moonlight: ['dreamy', 'romantic', 'atmospheric'],
  angry: ['angry', 'dark', 'atmospheric'],
  frustrated: ['angry', 'dark', 'melancholic'],
  mad: ['angry', 'dark', 'atmospheric'],
  rage: ['angry', 'dark', 'atmospheric'],
  resentful: ['dark', 'angry', 'melancholic'],
  jealous: ['dark', 'melancholic', 'atmospheric'],
  dreamy: ['dreamy', 'atmospheric', 'ambient'],
  aesthetic: ['dreamy', 'atmospheric', 'ambient'],
  ethereal: ['dreamy', 'atmospheric', 'ambient'],
  floating: ['dreamy', 'ambient', 'peaceful'],
  surreal: ['dreamy', 'atmospheric', 'dark'],
  magical: ['dreamy', 'happy', 'atmospheric'],
  haunted: ['dark', 'atmospheric', 'melancholic'],
  mysterious: ['dark', 'atmospheric', 'dreamy'],
  fog: ['atmospheric', 'dreamy', 'ambient'],
  hazy: ['atmospheric', 'dreamy', 'ambient'],
  warm: ['peaceful', 'chill', 'happy'],
  study: ['ambient', 'peaceful', 'atmospheric'],
  focus: ['ambient', 'peaceful', 'atmospheric'],
  working: ['ambient', 'atmospheric', 'peaceful'],
  productive: ['ambient', 'peaceful', 'atmospheric'],
  creative: ['dreamy', 'atmospheric', 'ambient'],
  thinking: ['atmospheric', 'ambient', 'melancholic'],
  reflective: ['melancholic', 'atmospheric', 'nostalgic'],
  healing: ['peaceful', 'ambient', 'happy'],
  weird: ['dark', 'atmospheric', 'dreamy'],
  restless: ['atmospheric', 'dark', 'melancholic'],
  anxious: ['dark', 'atmospheric', 'melancholic'],
  stressed: ['dark', 'atmospheric', 'angry'],
  overwhelmed: ['melancholic', 'dark', 'atmospheric'],
  wondering: ['dreamy', 'atmospheric', 'peaceful'],
};

export function getMoodTags(input: string): string[] {
  const words = input.toLowerCase().split(/\s+/);
  const tags = new Set<string>();

  words.forEach((word) => {
    const cleanWord = word.replace(/[^a-z0-9]/g, '');
    if (moodMap[cleanWord]) {
      moodMap[cleanWord].forEach((tag) => tags.add(tag));
    }
  });

  if (tags.size === 0) {
    ['chill', 'melancholic', 'atmospheric'].forEach((t) => tags.add(t));
  }

  return Array.from(tags).slice(0, 3);
}

export const MOOD_OPTIONS = [
  'angry',
  'anxious',
  'bittersweet',
  'blessed',
  'bored',
  'broken',
  'calm',
  'chill',
  'comfortable',
  'confident',
  'content',
  'cozy',
  'crying',
  'dark',
  'defeated',
  'depressed',
  'disappointed',
  'drained',
  'dreamy',
  'empty',
  'ethereal',
  'euphoric',
  'excited',
  'floating',
  'focused',
  'frustrated',
  'grateful',
  'grief',
  'haunted',
  'healing',
  'heartbroken',
  'hollow',
  'hopeful',
  'hopeless',
  'hurt',
  'hype',
  'in love',
  'jealous',
  'lazy',
  'lonely',
  'longing',
  'lost',
  'mad',
  'magical',
  'meh',
  'melancholic',
  'missing someone',
  'motivated',
  'mysterious',
  'nostalgic',
  'numb',
  'optimistic',
  'overwhelmed',
  'peaceful',
  'proud',
  'rage',
  'reflective',
  'regretful',
  'relaxed',
  'restless',
  'romantic',
  'sad',
  'sleepy',
  'stressed',
  'tender',
  'tired',
  'unstoppable',
  'warm',
  'yearning',
];